/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query an Agent by ID (?id=...) or list all agents */
        get: operations["get_or_list_agents_api_v1_agents_get"];
        put?: never;
        /** Register a new Agent Definition */
        post: operations["create_agent_api_v1_agents_post"];
        /** Delete an Agent by ID (?id=...) with optional force cleanup of local evaluation records */
        delete: operations["delete_agent_api_v1_agents_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Irreversibly purge an Agent and its local evaluation records with exact name confirmation */
        post: operations["purge_agent_api_v1_agents_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Agent Versions by agent_id and optional version (?agent_id=...&version=...) */
        get: operations["get_or_list_agent_versions_api_v1_agent_versions_get"];
        put?: never;
        /** Register a new immutable Agent Version specification */
        post: operations["create_agent_version_api_v1_agent_versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-versions/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive/deactivate an Agent Version (Body: {agent_id, version}) */
        post: operations["archive_agent_version_api_v1_agent_versions_archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Experiment Launch by ID (?id=...) or list all with optional filters */
        get: operations["get_or_list_launches_api_v1_experiment_launches_get"];
        put?: never;
        /** Create an Experiment Launch with frozen 4D Manifest & Idempotency */
        post: operations["create_experiment_launch_api_v1_experiment_launches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger asynchronous execution of a PENDING Experiment Launch */
        post: operations["run_launch_async_api_v1_experiment_launches__launch_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collaboratively cancel a running or queued Experiment Launch */
        post: operations["cancel_launch_api_v1_experiment_launches__launch_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume cancelled or failed items in an Experiment Launch */
        post: operations["resume_launch_api_v1_experiment_launches__launch_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry failed and timed out items in an Experiment Launch */
        post: operations["retry_failed_launch_api_v1_experiment_launches__launch_id__retry_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Experiment Launch detail by Launch ID */
        get: operations["get_launch_detail_api_v1_experiment_launches__launch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/{launch_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List item executions for a Launch with optional status filter and pagination */
        get: operations["list_launch_items_by_launch_id_api_v1_experiment_launches__launch_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launch-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List item executions for a Launch (?launch_id=...) */
        get: operations["list_launch_items_api_v1_experiment_launch_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-item-executions/{item_execution_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List execution attempts for an item execution */
        get: operations["list_item_attempts_by_item_id_api_v1_experiment_item_executions__item_execution_id__attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execution-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List execution attempts for an item (?item_execution_id=...) */
        get: operations["list_execution_attempts_api_v1_execution_attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiment-launches/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronously run an existing Experiment Launch (Atomic execution lock) */
        post: operations["run_experiment_launch_api_v1_experiment_launches_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all registered Evaluators and their specifications */
        get: operations["list_evaluators_api_v1_evaluators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Argus Control Plane runtime build and environment information */
        get: operations["get_system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap
         * @description Create/upsert the demonstration dataset in Langfuse.
         *
         *     Deterministic dataset-item UUIDs make the operation idempotent.
         */
        post: operations["bootstrap_admin_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Experiment */
        post: operations["run_experiment_experiments_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreateRequest */
        AgentCreateRequest: {
            /**
             * Id
             * @description Unique Agent identifier, e.g. banking-agent
             */
            id: string;
            /**
             * Name
             * @description Human-readable name
             */
            name: string;
            /**
             * Description
             * @description Detailed description
             */
            description?: string | null;
            /**
             * Owner
             * @description Team or owner identifier
             */
            owner?: string | null;
        };
        /** AgentDeleteResponse */
        AgentDeleteResponse: {
            /**
             * Id
             * @description ID of deleted Agent
             */
            id: string;
            /**
             * Deleted
             * @description Whether the Agent was successfully deleted
             * @default true
             */
            deleted: boolean;
            /**
             * Launches Deleted
             * @description Number of associated experiment launches cleaned up
             * @default 0
             */
            launches_deleted: number;
            /**
             * Message
             * @default Agent deleted successfully
             */
            message: string;
        };
        /** AgentPurgeRequest */
        AgentPurgeRequest: {
            /**
             * Agent Id
             * @description Agent ID to permanently purge
             */
            agent_id: string;
            /**
             * Confirm Name
             * @description Exact agent name to confirm irreversible purge
             */
            confirm_name: string;
        };
        /** AgentResponse */
        AgentResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Status */
            status: string;
            /**
             * Version Count
             * @default 0
             */
            version_count: number;
            /** Latest Version */
            latest_version?: string | null;
            /**
             * Launch Count
             * @default 0
             */
            launch_count: number;
            /**
             * Active Launch Count
             * @default 0
             */
            active_launch_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentSummaryResponse */
        AgentSummaryResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Status */
            status: string;
            /**
             * Version Count
             * @default 0
             */
            version_count: number;
            /** Latest Version */
            latest_version?: string | null;
            /**
             * Launch Count
             * @default 0
             */
            launch_count: number;
            /**
             * Active Launch Count
             * @default 0
             */
            active_launch_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentVersionArchiveRequest */
        AgentVersionArchiveRequest: {
            /** Agent Id */
            agent_id: string;
            /** Version */
            version: string;
        };
        /** AgentVersionCreateRequest */
        AgentVersionCreateRequest: {
            /**
             * Endpoint
             * @description HTTP POST URL of the agent
             */
            endpoint: string;
            /**
             * Protocol
             * @description Invocation protocol, currently HTTP_JSON only
             * @default HTTP_JSON
             */
            protocol: string;
            /**
             * Method
             * @description HTTP method, currently POST only
             * @default POST
             */
            method: string;
            /**
             * Request Mapping
             * @description Dot-path field mapping
             */
            request_mapping?: {
                [key: string]: string;
            };
            /** Request Schema */
            request_schema?: {
                [key: string]: unknown;
            } | null;
            /** Response Schema */
            response_schema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Credential Ref
             * @description Reference to secret, e.g. env://NAME
             */
            credential_ref?: string | null;
            /**
             * Timeout Seconds
             * @default 30
             */
            timeout_seconds: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
            /**
             * Rate Limit Per Minute
             * @default 600
             */
            rate_limit_per_minute: number;
            /**
             * Max Concurrency
             * @default 4
             */
            max_concurrency: number;
            /**
             * Trace Propagation
             * @description Trace context propagation standard, W3C only
             * @default W3C
             */
            trace_propagation: string;
            /**
             * Is Idempotent
             * @description Whether remote call has no side-effects and is safe to retry on read timeout
             * @default false
             */
            is_idempotent: boolean;
            /**
             * Artifact Ref
             * @description Commit SHA or image digest
             */
            artifact_ref?: string | null;
            /** Environment */
            environment?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Agent Id
             * @description Parent agent ID
             */
            agent_id: string;
            /**
             * Version
             * @description Version tag, e.g. v1, 2.0.0
             */
            version: string;
        };
        /** AgentVersionResponse */
        AgentVersionResponse: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Version */
            version: string;
            /** Spec Digest */
            spec_digest: string;
            /** Artifact Ref */
            artifact_ref?: string | null;
            /** Endpoint */
            endpoint: string;
            /** Protocol */
            protocol: string;
            /** Method */
            method: string;
            /** Request Mapping */
            request_mapping: {
                [key: string]: unknown;
            };
            /** Request Schema */
            request_schema?: {
                [key: string]: unknown;
            } | null;
            /** Response Schema */
            response_schema?: {
                [key: string]: unknown;
            } | null;
            /** Credential Ref */
            credential_ref?: string | null;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Max Retries */
            max_retries: number;
            /** Rate Limit Per Minute */
            rate_limit_per_minute: number;
            /** Max Concurrency */
            max_concurrency: number;
            /** Trace Propagation */
            trace_propagation: string;
            /** Is Idempotent */
            is_idempotent: boolean;
            /** Environment */
            environment?: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BootstrapResult */
        BootstrapResult: {
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Items Upserted */
            items_upserted: number;
        };
        /** DomainErrorResponse */
        DomainErrorResponse: {
            /**
             * Code
             * @description Machine-readable error code
             */
            code: string;
            /**
             * Detail
             * @description Human-readable explanation
             */
            detail: string;
            /**
             * Launch Count
             * @description Associated launch count if applicable
             */
            launch_count?: number | null;
            /**
             * Active Launch Count
             * @description Active launch count if applicable
             */
            active_launch_count?: number | null;
        };
        /** EvaluatorResponse */
        EvaluatorResponse: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Scope */
            scope: string;
            /** Threshold */
            threshold: number;
            /** Description */
            description?: string | null;
            /**
             * Default Selected
             * @default false
             */
            default_selected: boolean;
            /** Composed Of */
            composed_of?: string[];
        };
        /** ExecutionAttemptResponse */
        ExecutionAttemptResponse: {
            /** Id */
            id: string;
            /** Item Execution Id */
            item_execution_id: string;
            /** Attempt No */
            attempt_no: number;
            /** Status */
            status: string;
            /** Http Status */
            http_status?: number | null;
            /** Error Type */
            error_type?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Trace Context Received */
            trace_context_received: boolean;
            /** Worker Id */
            worker_id?: string | null;
            /**
             * Request Phase
             * @default PREPARED
             */
            request_phase: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ExperimentItemExecutionResponse */
        ExperimentItemExecutionResponse: {
            /** Id */
            id: string;
            /** Launch Id */
            launch_id: string;
            /** Dataset Item Id */
            dataset_item_id: string;
            /** Execution Status */
            execution_status: string;
            /** Eval Status */
            eval_status: string;
            /** Quality Conclusion */
            quality_conclusion: string;
            /** Execution Error */
            execution_error?: string | null;
            /** Eval Error */
            eval_error?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /** Observation Id */
            observation_id?: string | null;
            /** Final Attempt Id */
            final_attempt_id?: string | null;
            /** Scores */
            scores?: {
                [key: string]: unknown;
            } | null;
            /**
             * Attempt Count
             * @default 0
             */
            attempt_count: number;
            /** Final Attempt Http Status */
            final_attempt_http_status?: number | null;
            /** Final Attempt Latency Ms */
            final_attempt_latency_ms?: number | null;
            /** Queued At */
            queued_at?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Lease Owner */
            lease_owner?: string | null;
            /**
             * Dispatch Generation
             * @default 1
             */
            dispatch_generation: number;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ExperimentLaunchCreateRequest */
        ExperimentLaunchCreateRequest: {
            /**
             * Name
             * @description Optional experiment name
             */
            name?: string | null;
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version */
            dataset_version?: string | null;
            /**
             * Evaluator Ids
             * @description List of item-scope evaluator IDs to run; must contain at least one evaluator. Run-scope evaluators are not supported by the standalone launch runner.
             */
            evaluator_ids?: string[];
            /**
             * Max Concurrency
             * @description Optional concurrency override; if omitted, inherits from AgentVersion
             */
            max_concurrency?: number | null;
            /**
             * Idempotency Key
             * @description Optional idempotency key (can also be passed via Idempotency-Key header)
             */
            idempotency_key?: string | null;
        };
        /** ExperimentLaunchProgressResponse */
        ExperimentLaunchProgressResponse: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Retry Wait
             * @default 0
             */
            retry_wait: number;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Timed Out
             * @default 0
             */
            timed_out: number;
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Percentage
             * @default 0
             */
            percentage: number;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /** Allowed Actions */
            allowed_actions?: string[];
            /** Action Reasons */
            action_reasons?: {
                [key: string]: string;
            };
        };
        /** ExperimentLaunchResponse */
        ExperimentLaunchResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Quality Conclusion */
            quality_conclusion: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version */
            dataset_version?: string | null;
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /** Agent Version Id */
            agent_version_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Langfuse Experiment Id */
            langfuse_experiment_id?: string | null;
            /** Langfuse Experiment Url */
            langfuse_experiment_url?: string | null;
            /** Langfuse Sync Status */
            langfuse_sync_status: string;
            /** Langfuse Sync Error */
            langfuse_sync_error?: string | null;
            /** Links */
            links?: {
                [key: string]: string | null;
            } | null;
            progress?: components["schemas"]["ExperimentLaunchProgressResponse"] | null;
            /** Cancel Requested At */
            cancel_requested_at?: string | null;
            /** Status Reason */
            status_reason?: string | null;
            /** Allowed Actions */
            allowed_actions?: string[];
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ExperimentLaunchRunActionResponse */
        ExperimentLaunchRunActionResponse: {
            /** Launch Id */
            launch_id: string;
            /** Status */
            status: string;
            /**
             * Message
             * @default Launch queued for asynchronous execution
             */
            message: string;
        };
        /** ExperimentLaunchRunRequest */
        ExperimentLaunchRunRequest: {
            /**
             * Launch Id
             * @description ID of the launch to execute
             */
            launch_id: string;
        };
        /** ExperimentRequest */
        ExperimentRequest: {
            /**
             * Agent Id
             * @default banking-agent
             */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /**
             * Dataset Name
             * @default banking-agent-regression
             */
            dataset_name: string;
            /** Experiment Name */
            experiment_name?: string | null;
            /**
             * Max Concurrency
             * @description Optional concurrency override; if omitted, inherits from AgentVersion
             */
            max_concurrency?: number | null;
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Launch Id */
            launch_id: string;
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /** Experiment Name */
            experiment_name: string;
            /** Dataset Run Url */
            dataset_run_url?: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RetryFailedRequest */
        RetryFailedRequest: {
            /**
             * Force
             * @description Force retry even if ambiguous non-idempotent outcomes exist
             * @default false
             */
            force: boolean;
        };
        /** SystemInfoResponse */
        SystemInfoResponse: {
            /**
             * Service
             * @default argus-control-plane
             */
            service: string;
            /** Version */
            version: string;
            /** Build Id */
            build_id: string;
            /** Environment */
            environment: string;
            /** Langfuse Dashboard Url */
            langfuse_dashboard_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_or_list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                /** @description Optional Agent ID. If omitted, returns all agents. */
                id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"] | components["schemas"]["AgentSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_v1_agents_delete: {
        parameters: {
            query: {
                /** @description Agent ID to delete (required) */
                id: string;
                /** @description Whether to cascade delete local evaluation records. */
                force?: boolean;
            };
            header?: {
                /** @description Agent exact name to confirm force purge */
                "X-Confirm-Name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDeleteResponse"];
                };
            };
            /** @description Name confirmation mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Agent has associated launches or active tasks */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_agent_api_v1_agents_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPurgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDeleteResponse"];
                };
            };
            /** @description Name confirmation mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Active tasks in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_or_list_agent_versions_api_v1_agent_versions_get: {
        parameters: {
            query: {
                /** @description Agent ID (required) */
                agent_id: string;
                /** @description Optional version. If omitted, returns all versions of the agent. */
                version?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionResponse"] | components["schemas"]["AgentVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_version_api_v1_agent_versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentVersionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_agent_version_api_v1_agent_versions_archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentVersionArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_or_list_launches_api_v1_experiment_launches_get: {
        parameters: {
            query?: {
                /** @description Optional Launch ID. If omitted, returns all launches. */
                id?: string | null;
                /** @description Optional filter by Agent ID */
                agent_id?: string | null;
                /** @description Optional filter by execution status */
                status?: string | null;
                /** @description Optional filter by quality conclusion */
                quality_conclusion?: string | null;
                /** @description Optional limit */
                limit?: number | null;
                /** @description Optional offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"] | components["schemas"]["ExperimentLaunchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_launch_api_v1_experiment_launches_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentLaunchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_launch_async_api_v1_experiment_launches__launch_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchRunActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_launch_api_v1_experiment_launches__launch_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_launch_api_v1_experiment_launches__launch_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_failed_launch_api_v1_experiment_launches__launch_id__retry_failed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RetryFailedRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_launch_detail_api_v1_experiment_launches__launch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_launch_items_by_launch_id_api_v1_experiment_launches__launch_id__items_get: {
        parameters: {
            query?: {
                /** @description Optional execution status filter (e.g. cancelled, failed) */
                status?: string | null;
                /** @description Optional limit */
                limit?: number | null;
                /** @description Optional offset */
                offset?: number;
            };
            header?: never;
            path: {
                launch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentItemExecutionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_launch_items_api_v1_experiment_launch_items_get: {
        parameters: {
            query: {
                /** @description Launch ID (required) */
                launch_id: string;
                /** @description Optional execution status filter */
                status?: string | null;
                /** @description Optional limit */
                limit?: number | null;
                /** @description Optional offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentItemExecutionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_item_attempts_by_item_id_api_v1_experiment_item_executions__item_execution_id__attempts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionAttemptResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_execution_attempts_api_v1_execution_attempts_get: {
        parameters: {
            query: {
                /** @description Item Execution ID (required) */
                item_execution_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionAttemptResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_experiment_launch_api_v1_experiment_launches_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentLaunchRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentLaunchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluators_api_v1_evaluators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorResponse"][];
                };
            };
        };
    };
    get_system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    agents_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    bootstrap_admin_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResult"];
                };
            };
        };
    };
    run_experiment_experiments_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
